name: Trigger auto deployment for mister-ed-test-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/mister-ed-test-app-AutoDeployTrigger-fbd57e5f-1ea0-4bb5-87c7-43da43b58425.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MISTEREDTESTAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: dotnetcoresqldb20231017081000.azurecr.io
          registryUsername: ${{ secrets.MISTEREDTESTAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MISTEREDTESTAPP_REGISTRY_PASSWORD }}
          containerAppName: mister-ed-test-app
          resourceGroup: SENG350
          imageToBuild: dotnetcoresqldb20231017081000.azurecr.io/mister-ed-test-app:${{ github.sha }}
          

     

